// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type FwCidrKey struct {
	PrefixLen uint32
	Id        uint32
	Addr      uint32
}

type FwCidrValue struct {
	InnerId  uint32
	NextCidr FwCidrKey
}

type FwPktStats struct {
	Pkts  uint64
	Bytes uint64
}

type FwPortKey struct {
	Id   uint32
	Port uint32
}

type FwProtoKey struct {
	Id    uint32
	Proto uint16
	Pad1  uint16
}

type FwRuleAttrs struct {
	Action   uint32
	Id       uint32
	Priority uint32
}

// LoadFw returns the embedded CollectionSpec for Fw.
func LoadFw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FwBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Fw: %w", err)
	}

	return spec, err
}

// LoadFwObjects loads Fw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FwObjects
//	*FwPrograms
//	*FwMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFwObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FwSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FwSpecs struct {
	FwProgramSpecs
	FwMapSpecs
	FwVariableSpecs
}

// FwProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FwProgramSpecs struct {
	Fw *ebpf.ProgramSpec `ebpf:"fw"`
}

// FwMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FwMapSpecs struct {
	DstCidrMap *ebpf.MapSpec `ebpf:"dst_cidr_map"`
	DstPortMap *ebpf.MapSpec `ebpf:"dst_port_map"`
	ProtoMap   *ebpf.MapSpec `ebpf:"proto_map"`
	SrcCidrMap *ebpf.MapSpec `ebpf:"src_cidr_map"`
	SrcPortMap *ebpf.MapSpec `ebpf:"src_port_map"`
	Stats      *ebpf.MapSpec `ebpf:"stats"`
}

// FwVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FwVariableSpecs struct {
}

// FwObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFwObjects or ebpf.CollectionSpec.LoadAndAssign.
type FwObjects struct {
	FwPrograms
	FwMaps
	FwVariables
}

func (o *FwObjects) Close() error {
	return _FwClose(
		&o.FwPrograms,
		&o.FwMaps,
	)
}

// FwMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFwObjects or ebpf.CollectionSpec.LoadAndAssign.
type FwMaps struct {
	DstCidrMap *ebpf.Map `ebpf:"dst_cidr_map"`
	DstPortMap *ebpf.Map `ebpf:"dst_port_map"`
	ProtoMap   *ebpf.Map `ebpf:"proto_map"`
	SrcCidrMap *ebpf.Map `ebpf:"src_cidr_map"`
	SrcPortMap *ebpf.Map `ebpf:"src_port_map"`
	Stats      *ebpf.Map `ebpf:"stats"`
}

func (m *FwMaps) Close() error {
	return _FwClose(
		m.DstCidrMap,
		m.DstPortMap,
		m.ProtoMap,
		m.SrcCidrMap,
		m.SrcPortMap,
		m.Stats,
	)
}

// FwVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFwObjects or ebpf.CollectionSpec.LoadAndAssign.
type FwVariables struct {
}

// FwPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFwObjects or ebpf.CollectionSpec.LoadAndAssign.
type FwPrograms struct {
	Fw *ebpf.Program `ebpf:"fw"`
}

func (p *FwPrograms) Close() error {
	return _FwClose(
		p.Fw,
	)
}

func _FwClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fw_x86_bpfel.o
var _FwBytes []byte
